name: nodejs App Build
on: 
  push: 
    branches: 
     - master
jobs:
  Build-job1:
   continue-on-error: true
   strategy:
    matrix:
     node-version: [12,14,16]
     operating-system: [ubuntu-latest,windows-latest]
     exclude: 
      - node-version: 12
        operating-system: windows-latest 
   runs-on: ${{matrix.operating-system}}
   steps:
     - name: Clone the repo
       uses: actions/checkout@v4
     - name: install nodejs
       uses: actions/setup-node@v3
       with:
          node-version: ${{matrix.node-version}}      
     - name: Install Dependencies
       run: npm ci
     - name: test code
       run: npm run test
     - name: Upload test report on github
       uses: actions/upload-artifact@v4
       with:
         name: test-report
         path: test.json
